// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nycthemeron.API.Data;

#nullable disable

namespace Nycthemeron.API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251103094611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CharacterSheetTalent", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TalentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharactersId", "TalentsId");

                    b.HasIndex("TalentsId");

                    b.ToTable("CharacterSheetTalent", (string)null);
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterSheetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charges")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoonAbilityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoonActionTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoonRequirements")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoonRuleText")
                        .HasColumnType("TEXT");

                    b.Property<int>("MoonSpiritCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoonTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("SunAbilityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SunActionTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SunRequirements")
                        .HasColumnType("TEXT");

                    b.Property<string>("SunRuleText")
                        .HasColumnType("TEXT");

                    b.Property<int>("SunSpiritCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SunTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.CharacterAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aspiration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CharacterAttribute", (string)null);
                });

            modelBuilder.Entity("Nycthemeron.API.Models.CharacterSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT");

                    b.Property<int>("AgilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseArmor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpirit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentArmor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHitpoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentSpirit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicalArmor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHitpoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MindId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Movement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MysticId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PresenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Race")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalentPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempHitpoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgilityId");

                    b.HasIndex("BodyId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MindId");

                    b.HasIndex("MysticId");

                    b.HasIndex("PresenceId");

                    b.HasIndex("UserId");

                    b.ToTable("CharacterSheet", (string)null);
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameMasterId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterSheetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EquippedArmorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MainHandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OffHandId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId")
                        .IsUnique();

                    b.HasIndex("EquippedArmorId");

                    b.HasIndex("MainHandId");

                    b.HasIndex("OffHandId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquippedSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("InventoryId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attribute")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TalentId");

                    b.ToTable("Requirement", (string)null);
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Talent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Talent", (string)null);
                });

            modelBuilder.Entity("Nycthemeron.API.Models.TalentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TalentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TalentId");

                    b.ToTable("TalentType", (string)null);
                });

            modelBuilder.Entity("Nycthemeron.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Nycthemeron.API.Models.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Accessory", b =>
                {
                    b.HasBaseType("Nycthemeron.API.Models.Item");

                    b.Property<string>("Effects")
                        .HasColumnType("TEXT");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Effects")
                                .HasColumnName("Accessory_Effects");
                        });

                    b.HasDiscriminator().HasValue("Accessory");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Armor", b =>
                {
                    b.HasBaseType("Nycthemeron.API.Models.Item");

                    b.Property<int>("ArmorValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effects")
                        .HasColumnType("TEXT");

                    b.Property<int>("Initative")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Penalties")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resistances")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Container", b =>
                {
                    b.HasBaseType("Nycthemeron.API.Models.Item");

                    b.Property<bool>("Equipped")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Container");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Other", b =>
                {
                    b.HasBaseType("Nycthemeron.API.Models.Item");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Other");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Weapon", b =>
                {
                    b.HasBaseType("Nycthemeron.API.Models.Item");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageTypes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effects")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grip")
                        .HasColumnType("TEXT");

                    b.Property<int>("InitativeMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementMod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Penalties")
                        .HasColumnType("TEXT");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReloadPenalty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightClass")
                        .HasColumnType("TEXT");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Effects")
                                .HasColumnName("Weapon_Effects");

                            t.Property("Penalties")
                                .HasColumnName("Weapon_Penalties");
                        });

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("CharacterSheetTalent", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nycthemeron.API.Models.Talent", null)
                        .WithMany()
                        .HasForeignKey("TalentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Card", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.CharacterSheet", null)
                        .WithMany("Cards")
                        .HasForeignKey("CharacterSheetId");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.CharacterSheet", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.CharacterAttribute", "Agility")
                        .WithMany()
                        .HasForeignKey("AgilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nycthemeron.API.Models.CharacterAttribute", "Body")
                        .WithMany()
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nycthemeron.API.Models.Group", "Group")
                        .WithMany("Characters")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nycthemeron.API.Models.CharacterAttribute", "Mind")
                        .WithMany()
                        .HasForeignKey("MindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nycthemeron.API.Models.CharacterAttribute", "Mystic")
                        .WithMany()
                        .HasForeignKey("MysticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nycthemeron.API.Models.CharacterAttribute", "Presence")
                        .WithMany()
                        .HasForeignKey("PresenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nycthemeron.API.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agility");

                    b.Navigation("Body");

                    b.Navigation("Group");

                    b.Navigation("Mind");

                    b.Navigation("Mystic");

                    b.Navigation("Presence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Group", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.User", "GameMaster")
                        .WithMany("ManagedGroups")
                        .HasForeignKey("GameMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMaster");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Inventory", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.CharacterSheet", "CharacterSheet")
                        .WithOne("Inventory")
                        .HasForeignKey("Nycthemeron.API.Models.Inventory", "CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nycthemeron.API.Models.Armor", "EquippedArmor")
                        .WithMany()
                        .HasForeignKey("EquippedArmorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nycthemeron.API.Models.Weapon", "MainHand")
                        .WithMany()
                        .HasForeignKey("MainHandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nycthemeron.API.Models.Weapon", "OffHand")
                        .WithMany()
                        .HasForeignKey("OffHandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CharacterSheet");

                    b.Navigation("EquippedArmor");

                    b.Navigation("MainHand");

                    b.Navigation("OffHand");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Item", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.Container", "Container")
                        .WithMany("ContainingItems")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nycthemeron.API.Models.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Container");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Requirement", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.Talent", "Talent")
                        .WithMany("Requirements")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.TalentType", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.Talent", "Talent")
                        .WithMany("TalentTypes")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.User", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.Group", null)
                        .WithMany("ActiveUsers")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.UserGroup", b =>
                {
                    b.HasOne("Nycthemeron.API.Models.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nycthemeron.API.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.CharacterSheet", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Group", b =>
                {
                    b.Navigation("ActiveUsers");

                    b.Navigation("Characters");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Talent", b =>
                {
                    b.Navigation("Requirements");

                    b.Navigation("TalentTypes");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("ManagedGroups");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Nycthemeron.API.Models.Container", b =>
                {
                    b.Navigation("ContainingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
